fixes + removed final field stuff due to a "java.lang.NoSuchMethodError" on server + fixed last remaining Platinum reverse recipes for Dreamcraft/GT Items + fixed a typo in the centrifuge recipe + added a circuit priorisation mode for the MEGA EBF + redid the CircuitAssemblyLine Structure-Check + version increase to match testing version
Signed-off-by: bartimaeusnek <33183715+bartimaeusnek@users.noreply.github.com>

Former-commit-id: 52953b263c61587acf618d21f4eea942b61edb5b